### ISSUE TITLE
Contrastive Clustering？

### ISSUE THREAD

**Issue by kike-0304** [ZhiyuanDang/DCDC#2]
Is this work different from Contrastive Clustering (CC)? The effect of Contrastive Clustering is better.

**Comment by ZhiyuanDang** [comment]
There are a few differences between our DCDC and CC, such as that they use two heads for two losses as we share one head for two losses, they run 1000 epochs as we run 200 epochs.

Actually, our DCDC and CC are simultaneously submitted to AAAI 2022. CC is accepted and DCDC is not.
